image:
  file: .gitpod.Dockerfile

tasks:
#  - init: juliaup run 1.7 setup
#   - command: julia --project=@. -e 'using Pluto; Pluto.run(port=8000, launch_browser=false, require_secret_for_open_links=false)'
  - command: julia --project=@. -e  'using Franklin; newsite("mySite", template="vela"); pwd(); serve()'

ports:
  - port: 8000
    onOpen: open-preview
  #- port: 8000
  #  onOpen: open-browser
